# Generated by Django 3.1.6 on 2021-02-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.CharField(default='Latest Movies', max_length=500),
            preserve_default=False,
        ),
    ]
